### ISSUE TITLE
Can it be used for TBS series oscilloscope？

### ISSUE THREAD

**Issue by isCopyman** [tektronix/curvequery#48]
If I want to read waveform data through Python, and then transmit it to the web front-end in real time, I can control the scale of the oscilloscope through the web. Is there any way.

**Comment by cwstryker** [comment]
Curve Query does not currently support TBS oscilloscopes.  Curve Query is scalable and new oscilloscopes can be added.  However, someone would need to do the work of creating a download routine and adding it to Curve Query.
